Repository octokit/auth-callback.js, pull requests merged in 2023-06, with the labels that each got.

#154 fix(build): switch to esbuild
  package-lock.json
  package.json
  scripts/build.mjs
  src/auth.ts
  src/hook.ts
  src/index.ts
  test/tsconfig.test.json
  tsconfig.json
Labels: Type: Maintenance

#148 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: Type: Breaking change, Type: Maintenance

#157 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation
